### ISSUE TITLE
[GUI] bzr crashes when launched with undocked windows

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#102]
i've undocked 2 windows then closed bzr2, now it won't starts anymore. i'm unable to replicate it through specific actions but u can inspect the faulty windowState:
[settings.zip](https://github.com/aargirakis/BZRPlayer/files/9439446/settings.zip)
workaround: delete windowState from settings.ini

**Comment by aargirakis** [comment]
This was caused when the current playlist window was docked.
