### ISSUE TITLE
channels not correctly muted

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#104]
muting all channels will not mute everything: some muting are ignored
[fallbiod.zip](https://github.com/aargirakis/BZRPlayer/files/9439949/fallbiod.zip)

**Comment by aargirakis** [comment]
The same bug is also present in BZR Player v1. It some weird bug in the libxmp plugin. Very strange, must be some unitialized variable/error in memory that causes this weird behaviour.

**Comment by ciros88** [comment]
bug still present using libopenmpt
