### ISSUE TITLE
mp3 files that can't be played

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#108]
Although BZRPlayer is very good at playing mp3 files, but this is one of those rare mp3 files that BZRPlayer can't play it.

[pom.zip](https://github.com/aargirakis/BZRPlayer/files/9458747/pom.zip)

**Comment by ciros88** [comment]
it also fails on bzr1

**Comment by aargirakis** [comment]
Yes, I'm guessing it's a bug in FMOD. I'll check their forum.

**Comment by ciros88** [comment]
this one fails in bzr2, bzr1 & zxtune also (not in vlc):
[Cheb Mami - Hay wadi hay galbi.zip](https://github.com/aargirakis/BZRPlayer/files/9690604/Cheb.Mami.-.Hay.wadi.hay.galbi.zip)

**Comment by aargirakis** [comment]
Plays in Foobar, plays in Chrome.
Not in XMPlay, not in Windows Media Player, not in Adobe Audition, Mp3 Tag says MPEG 1 Layer I.
So I'm guessing it's corrupt. But I can check the FMOD forum.

**Comment by rayman3003** [comment]
> Not in XMPlay

If u r talking about my uploaded file, pom.mp3

Nope. It can be played in XMPlay. (v3.8.5.31)

Also it can be played in AIMP, Winamp, Xion,...

So I don't think it is corrupted.

**Comment by ciros88** [comment]
now bzr2 play both of them thru vgmstream
