### ISSUE TITLE
Some ogg files can't be played in BZRPlayer

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#109]
I found some few ogg files that can't be played in BZRPlayer.

Here is an example:

[story2.zip](https://github.com/aargirakis/BZRPlayer/files/9458762/story2.zip)

**Comment by ciros88** [comment]
tested with 2.013.Alpha & 2.0.14.Alpha:
it works fine here.
which version do u used?

**Comment by rayman3003** [comment]
I was talking about BZRPlayer 1.06.

Where can I download the last beta 2.0? Bcuz there is no release available in the release section of github.

**Comment by rayman3003** [comment]
OK. Found 2.0.14.Alpha in patreon. But it asks for payment subscription, to download the BZR!

What does it mean?

**Comment by ciros88** [comment]
patreon is born with this policy: supporting projects. for bzr2 player, in my opinion, its really worth to support it: actually for what i know it is the player with the most extended list of supported (exotic) audio file formats

**Comment by rayman3003** [comment]
> patreon is born with this policy: supporting projects. for bzr2 player, in my opinion, its really worth to support it: actually for what i know it is the player with the most extended list of supported (exotic) audio file formats

Does this mean that BZRPlayer2 is a permanent commercial app? Or it is temporary?

**Comment by ciros88** [comment]
for what i know, it is only for supporting/motivate dev in alpha (or also beta stage), but it will released as free like bzr1

**Comment by rayman3003** [comment]
> for what i know, it is only for supporting/motivate dev in alpha (or also beta stage), but it will released as free like bzr1

OK. If the final version is going to be free, it's good.
