### ISSUE TITLE
The BZRPlayer crashes when playing more than 100-150 files

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#110]
BZRPlayer has a serious bug, when playing more than 100-150 files.

Just play more than 100-150 files (mp3 for example) with BZRPlayer & then suddenly BZRPlayer will be crashed.

I need to close the BZRPlayer process in task manager & re-open it again.

**Comment by ciros88** [comment]
I have a playlist of 647 mp3s, and works fine (also loading is really fast)
can u provide some useful infos, like version used and better describe the behaviour, which files u use, when exactly it crashes (when adding all the files or trying to play one?)

**Comment by rayman3003** [comment]
I use the last version (1.06).

It doesn't matter which file I use, any mp3 files (& probably any ogg files) that are more than 100-150 numbers, makes the BzrPlayer to crash.

It crashes when it plays more than 100-150 files. It doesn't matter if all 100-150 files in one folder, or in different playlists. For example:

I play 6 folders containing mp3 files 

(folder number 1 = 50 mp3 files)
(folder number 2 = 30 mp3 files)
(folder number 3 = 20 mp3 files)
(folder number 4 = 15 mp3 files)
(folder number 5 = 10 mp3 files)
(folder number 6 = 5 mp3 files)

The sum is = 130 mp3 files

The first 5 folders plays without problem, but in the middle of playing the folder number 6, Bzrplayer starts to crash.

**Comment by ciros88** [comment]
you are referring to bzrplayer 1.x serie, this repo is for bzr2 alpha development (alpha stage) read here:
https://github.com/aargirakis/BZRPlayer#readme
actually binaries are only released on aargirakis Patreon:
https://www.patreon.com/bzrplayer
