### ISSUE TITLE
[sc68] various issues

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#121]
some tracks not playing, some durations not displayed
[Huelsbeck Atari ST.zip](https://github.com/aargirakis/BZRPlayer/files/9484236/Huelsbeck.Atari.ST.zip)

**Comment by aargirakis** [comment]
Those files plays exactly like they do it BZR 1. So I'm guessing that:
SC68 might be buggy
There might be buggy rips
Song lentgh may not be supported for all files

**Comment by ciros88** [comment]
yeah, need to try with a "reliable" sc68 player

**Comment by ciros88** [comment]
another issue: Unknown Huelsbeck.sc68 (inside attachment) play last subsong first

**Comment by aargirakis** [comment]
I tried http://www.wothke.ch/webaudio68/ and it was about the same result as in BZR. So probably faulty files or bugs in sc68.

**Comment by ciros88** [comment]
almost all of them now play (maybe thanks to sc68 update in 2.0.74), just couple of subtunes require a double or triple play click in order to work. i think nothing else can be done here
