### ISSUE TITLE
set audio libraries output to 44khz by default (including libopenmpt)

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#123]

**Comment by aargirakis** [comment]
How/where do you see it's not 44100 hz? Only libopenmpt?

**Comment by ciros88** [comment]
with my ears xD i've noticed this with libopenmpt, so I thought its  better to be sure to set all libs to 44khz

**Comment by aargirakis** [comment]
Well AFAK all is set to 44.1 khz... also libopenmpt.
