### ISSUE TITLE
Silently skips a corrupted playlists/Default.m3u 

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#13]
i suppose user should be informed when bzr skips an incorrect playlist file

**Comment by ciros88** [comment]
an alert message could be appears, and playlist entry could be ~~displayed with strikethrough~~

**Comment by aargirakis** [comment]
What kind of corrupted file do you mean? Right now we only look at the file extension and load it no matter what. It's hard to see if an m3u is legal or not.

**Comment by ciros88** [comment]
i dont remember very well the behaviour encountered when i opened this issue.
now, after various releases, the behaviour of invalid file handling is changed.
but: try to put this playlist (that uses relative paths, but i don't know if this is the main cause) into "playlists" folder then open bzr2 and click on play button (not on the single tracks): it will crash, instead of marking its tracks as invalid/not_found.

[Coding - Caterina Barbieri.zip](https://github.com/aargirakis/BZRPlayer/files/9624497/Coding.-.Caterina.Barbieri.zip)

also, when quitting bzr2 that playlist will be saved with all tracks pointing playlists folder: what is the meaning of this behavior?

**Comment by aargirakis** [comment]
It doesn't crash any more.
