### ISSUE TITLE
[Settings] allow single app instance only

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#139]

**Comment by aargirakis** [comment]
But why really? You can start VLC how many times you want for example.

**Comment by ciros88** [comment]
https://www.vlchelp.com/enable-disable-multiple-instances/

The advantage of having one instance only is to be able to play in the same player instance each file you open from a file manager, without need to stop/close the other instances. As you can see in the link above, vlc has this feature: in single instance mode, opening a new file will adding this one to the current player playlist and immediately play it (stopping the previous track). Vlc has also another checkbox (that u can enable in single instance only) for queue files as playlist entries without play them :) i think single instance mode it is an useful feature

**Comment by aargirakis** [comment]
Ah ok. Yes, I've got the same feature in BZR 1.

**Comment by ciros88** [comment]
2.0.34.Alpha:
with one instance mode multiple bzr2 are opened.

btw, makes sense to test this feature only after #286 is done

**Comment by ciros88** [comment]
the problem is, altrough one instance mode is enabled from the settings, it is applied and saved only after bzr2 has been closed. this is why it behave as my previous comment. instead, it should be applied when it is enabled
