### ISSUE TITLE
missing subsongs (2.0.19Alpha regression)

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#144]
subsongs appear only after clicking one or more times for playing

[cust.zip](https://github.com/aargirakis/BZRPlayer/files/9624191/cust.zip)

i suppose it is linked to #138 resolution

**Comment by aargirakis** [comment]
That UADE is a real pain in the ass, strange bugs and random crashes...

**Comment by ciros88** [comment]
launch bzr2 with empty playlist, then add Simulcra and click on it for playing:
1 subsong is displayed and start playing, if u click twice 2 subsongs appears, but first one start playing something strange (like a kick, then an "explosion" and then endless hihats). now, if you clear playlist and re-drop simulcra and then click play, 2 subsongs are immediately recognized at the first try, but the first one starts playing silently.
really intricate, I know
[Simulcra.zip](https://github.com/aargirakis/BZRPlayer/files/9638160/Simulcra.zip)
