### ISSUE TITLE
If shuffle is enabled going back to the first shuffled track will always go to number 1 in the playlist

### ISSUE THREAD

**Issue by aargirakis** [aargirakis/BZRPlayer#163]

**Comment by ciros88** [comment]
something strange happens in 2.0.31.Alpha. 
try this scenario: open bzr2, than add some track, then enable shuffle and do play. then press the previous track button: nothing happens. 
i think we need to establish how to handle the shuffle and its history. in my opinion, shuffle can have an history but if we go to previous track with shuffle active and there is no shuffle history (that means, that track was the first played) then the back action should be random, as shuffle means to be intended.

**Comment by aargirakis** [comment]
I think this is fixed. Ragarding your comment about try this scenario: "open bzr2, than add some track, then enable shuffle and do play. then press the previous track button: nothing happens.", that is exactly how it's programmed to behave and also what I think is most normal from a user point of view,
