### ISSUE TITLE
[WRK] Not playable

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#175]
Found an audio format that can't be played in BZR2.

BZR's Version: 2.0.21 Alpha

Some samples:

WRK

[WRK.zip](https://github.com/aargirakis/BZRPlayer/files/9744739/WRK.zip)

**Comment by ciros88** [comment]
http://justsolve.archiveteam.org/wiki/Cakewalk_Project_(WRK)

**Comment by rayman3003** [comment]
This is a music file format. It says it contains midi files.

Midi = Music

**Comment by ciros88** [comment]
We discussed about it (on discord):
it isn't strictly a music file format but a Cakewalk project file, "loosely
based on midi. It is not intended to be played by itself, actually doesn't exist a *.wrk player library: only the Cakewalk software itself is able to play/render them

**Comment by rayman3003** [comment]
OK
