### ISSUE TITLE
[xm] BZR2 closes immediately, when playing xm files

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#177]
When I play any xm files, BZR2 closes itself immediately, no matter which kind of xm file it is trying to play.

Some sample files for you to try it yourself:

[xm.zip](https://github.com/aargirakis/BZRPlayer/files/9768485/xm.zip)

BZR's Version: 2.0.21 Alpha

**Comment by ciros88** [comment]
yeah, this is why 2.0.21.Alpha is an "internal" release, because there are known bugs due to working-in-progress with tracker view stuff. one of these bug is about XM crashes. they will be resolved in 2.0.22.Alpha for what i know. Thanks anyway for having reported it
