### ISSUE TITLE
[ay] Some ay files make BZR2 to crash

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#178]
Despite BZR2 can play most ay files without problem, But for some of them, BZR2 closes itself immediately, when playing those some files.

BZR's Version: 2.0.21 Alpha

Some samples:

ay

[ay.zip](https://github.com/aargirakis/BZRPlayer/files/9768651/ay.zip)

**Comment by aargirakis** [comment]
For some reason, those ay-files can't be recognized by Game Music Emu and so ZXTune plays them, but mosty crashes. So it's the same bug as #91
