### ISSUE TITLE
[emul] Some files can't be played

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#184]
Despite BZR2 can play most of the emul file format, But some few of them can't be played in BZR2, Or make the BZR2 to crashes!

BZR's Version: 2.0.21 Alpha

[emul.zip](https://github.com/aargirakis/BZRPlayer/files/9768765/emul.zip)

**Comment by ciros88** [comment]
these works in bzr1

**Comment by rayman3003** [comment]
> these works in bzr1

Yeap, I confirm too that BZR1 can kick their asses. :P
