### ISSUE TITLE
[MDX] Not playable

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#193]
Found an audio format that can't be played in BZR2.

BZR's Version: 2.0.21 Alpha

Note: I'm almost sure that they r music files, bcuz a lot of them named as BGM.

Some samples:

MDX

[MDX.zip](https://github.com/aargirakis/BZRPlayer/files/9768920/MDX.zip)

**Comment by ciros88** [comment]
successfully played using:
https://github.com/FIX94/in_mdx

i think this could be a solution for bzr2:
https://github.com/vampirefrog/mdxtools
