### ISSUE TITLE
change "remove selected files" action name to "remove selected tracks"

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#196]
subsongs support changes game-play rules: now there aren't 'files' anymore, but they are abstracted to 'tracks'

**Comment by aargirakis** [comment]
Well, you could also have webstreams and wav-files playing a sound of a car engine. So maybe files aren't 100% correct, but neither is tracks. Items is not wrong though. VLC says "Remove selected". Foobar says "Remove".

**Comment by ciros88** [comment]
good point. didn't used webstreams with bzr2 yet...
i suppose "remove selected" is the way
