### ISSUE TITLE
crash when trying to play an heavy IT track in a playlist (not alone)

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#198]
i think happens when IT tracks are heavy.
has been happened 3 times, now dunno how to reproduce it. i will try in next days
[it.zip](https://github.com/aargirakis/BZRPlayer/files/9793821/it.zip)

**Comment by aargirakis** [comment]
Tried them and the play fine although tracker view is really sluggish. BZR1 just crashes when loading them, so it's better than BZR1 at least.

**Comment by ciros88** [comment]
dunno what bzr1 version you are using: 1.0.6 here, and these playing flawlessly.
about bzr2, yeah they play fine when picked alone but when mixed with some other tracks bzr2 crash.

**Comment by ciros88** [comment]
has been happended just now, with 2.0.23 with this track:
[AMIGAMIX.ZIP](https://github.com/aargirakis/BZRPlayer/files/9817236/AMIGAMIX.ZIP)

that is..an heavy XM

**Comment by ciros88** [comment]
found how to reproduce it sometimes: launch bzr2 with a clearplaylist, then add these tracks into
[bug.zip](https://github.com/aargirakis/BZRPlayer/files/9817257/bug.zip)

play quartex2 first then amigamix, sometimes it crashes

**Comment by ciros88** [comment]
happened with 2.0.43.Alpha when playing this 'heavy' track after having pressed next multiple times on a playlist made by various file formats. not easy to reproduce.

https://easyupload.io/m5dvjg

**Comment by ciros88** [comment]
this doesn't happens anymore in my everyday use, i think has been fixed. i will close it
