### ISSUE TITLE
[Feauture request] Drag & dropping must start the playback imediately

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#200]
Currently, when drag & dropping any file to the BZR2, It adds to to playlist, but not playing it.

I think it must **play** it instead. (just like how BZR1 works).

Edit: I think this is the best behavior for drag & dropping:

A) When u want to use files from multiple sources, U just drag & drop them in the playlist window of BZR2. (New files will be added at the end of the current playlist; & will be played when their time comes)

B) But when u need to play just the current file(s) only, U drag & drop them in the main or other windows of the BZR2. (& BZR2 ignores & removes all the previous file(s) in the playlist; & then add & start to play only the newly added files)

**Comment by ciros88** [comment]
It is not a desidered automatism when you need to enquque files from multiple sources, so you need to do multiple drag and drops. I think that the current behaviour is better

**Comment by rayman3003** [comment]
> when you need to enquque files from multiple sources, so you need to do multiple drag and drops but don't want that bzr2 start play until you finish ur operations.

There is an easy solution for this:

When u want to use files from multiple sources, U just drag & drop them in the **playlist window** of BZR2. (New files will be added at the end of the current playlist; & will be played when their time comes)

But when u need to play just the current file(s) only, U drag & drop them in the **main or other windows** of the BZR2. (& BZR2 ignores & removes all the previous file(s) in the playlist; & then add & start to play only the newly added files)

**Comment by ciros88** [comment]
what many players do for this is to simply add a "play with" action in right click window menù (along with "enqueue in").
in this manner you can select files u want to play, then right click on them and do "play with bzr2"
(playlists windows have another scope, that is for playlists)

**Comment by rayman3003** [comment]
> and it is a faster action then drag and drop

It is not! Nothing is faster than drag & drop.

**Comment by ciros88** [comment]
is it faster because with drag and drop you need to "prepare" target to receive the sources from the file manager (eg explorer): this is not required through proposed solution.

**Comment by rayman3003** [comment]
> is it faster because with drag and drop you need to "prepare" target to receive the sources from the file manager (eg explorer):

Yeap, I use file manager (not explorer), but dual-pane managers (like xyplorer) that gives me a lot more options than explorer, or even the internal managers of audio players. Dual-pane managers are a lot faster than windows explorer or internal managers of audio players too.

So why should I prefer the slower with-less-options of internal managers of audio players, over a fast full-featured dual-pane file manager?

**Comment by ciros88** [comment]
yeah I also never used explorer (total commander all the life), but this is another problem and its scope is out of bzr2 development i suppose

**Comment by rayman3003** [comment]
> its scope is out of bzr2 development i suppose

What do u mean?

BZR1 support drag & drop!

**Comment by rayman3003** [comment]
> this type of coupling (in computer programming theory) should be avoided

I don't understand! Why it should avoided?!

When a dual-pane file manager, is faster & has more feature than the internal file manager of BZR2, why it must avoided?

Drag & drop support is not a very unique or obscure option. I don't understand why it must avoided.

BTW, If the internal file manger of BZR2 became a dual-pane, & also armed with some features (like file moving between two panes, deletion, renaming, tag editing & some few more), I have no problem with not having a drag & drop in BZR2.

Does the internal file manager of BZR2 is going to became dual-pane? I don't think so...

**Comment by ciros88** [comment]
this behaviour should depend on #139 checkbox "enqueue items"
