### ISSUE TITLE
[ama] Not playable

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#201]
A audio format that can't be played in BZR2.

BZR's Version: 2.0.22 Alpha

Note: I'm 100% sure that they r music files, bcuz BZR**1** can play them!

Some samples:

[ama.zip](https://github.com/aargirakis/BZRPlayer/files/9795757/ama.zip)

**Comment by aargirakis** [comment]
That zip-file is empty

**Comment by rayman3003** [comment]
> That zip-file is empty

Oh, sorry, my bad.

I re-uploaded it again. :P

**Comment by ciros88** [comment]
these are midi files (works in bzr1)

**Comment by rayman3003** [comment]
> these are midi files

OK. So fixing midi playback, would fix these too.

Please close this issue too.
