### ISSUE TITLE
[ym] some ym files crash the BZR2

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#203]
Despite BZR2 can play ym files, But a lot of the ym files make the BZR2 to crash. They can't be played in BZR2.

BZR's version: 2.0.22 Alpha

I'm 100% sure that these ym files are music:

samples:

[ym.zip](https://github.com/aargirakis/BZRPlayer/files/9800894/ym.zip)

**Comment by aargirakis** [comment]
Same as #91
