### ISSUE TITLE
tracker view artifacts

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#213]
when resizing:
![bug](https://user-images.githubusercontent.com/84340161/197327178-3e9cffc3-675b-4d21-bf7d-5fd2a1957584.gif)
this happens with xm also, i think happens when modules have many channels

**Comment by ciros88** [comment]
this happens with xm also, i think happens when modules have many channels

**Comment by ciros88** [comment]
fault refresh when changing tracks.
seem that correct refresh is done with ahx and mod, but not for it and xm (maybe because these one have many channels)
![bug](https://user-images.githubusercontent.com/84340161/197327442-97660f71-b0b1-4a75-b4b6-429133ae9f97.gif)

**Comment by aargirakis** [comment]
The stretching is not so much I can do about, it's the resize filter that's not the best in the world
