### ISSUE TITLE
Add vgmstream to BZR2

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#214]
**vgmstream** is a library for playback of various streamed audio formats used in video games.

https://github.com/vgmstream/vgmstream

It is open-source & adding it to BZR, would add the playback support of **100+** audio formats (mostly musics of games) to the BZR2.

Here is the list of supported formats:

https://github.com/vgmstream/vgmstream/blob/master/doc/FORMATS.md

What do u say?

Here is an example bgm file than can be played in foobar2000 (with vgmstream component installed):

[hca.zip](https://github.com/aargirakis/BZRPlayer/files/9844892/hca.zip)

**Comment by aargirakis** [comment]
Actually vgsmtream is already in BZR2, although it's a pretty old version.

**Comment by rayman3003** [comment]
> Actually vgsmtream is already in BZR2, although it's a pretty old version.

So r u going to update it to the last version? 😝

Bcuz that old version doesn't support the hca (or probably a lot other) format(s).

**Comment by aargirakis** [comment]
Actually I just compiled the latest version, it went well. Your attached file now works and as a bonus: seeking in vgmstream now also works.

**Comment by rayman3003** [comment]
> Actually I just compiled the latest version, it went well. Your attached file now works and as a bonus: seeking in vgmstream now also works.

Awesome. & thank u very much.

Now I will close this issue. :)

**Comment by ciros88** [comment]
Please close the issue after a proper testing only

**Comment by rayman3003** [comment]
> Please close the issue after a proper testing only

OK. From now on, I won't close any issues. U do the closings.
