### ISSUE TITLE
[orc] Not playable

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#229]
Found an audio format that can't be played in BZR2.

BZR's Version: 2.0.25 Alpha

Note: I'm almost sure that they r music files, bcuz a lot of them named as **song** or **theme**. & also a lot of them has the names of famous songs.

Some samples:

[orc.zip](https://github.com/aargirakis/BZRPlayer/files/9943639/orc.zip)

**Comment by ciros88** [comment]
these are Csound orchestra files,
adding support for playiing them not only it is not feasible, but its also out of bzr2 scope

**Comment by rayman3003** [comment]
> adding support for playing them it is not feasible

Can u explain more? Why It's not feasible? or out of BZR2 scope? Just curious to know.

**Comment by ciros88** [comment]
i also want to have a player more comprehensive as possible, but:
- after a long research i didn't found no library for playing that files: i think they simply don't exists
- there is something more complex under the hood compared to other track formats
