### ISSUE TITLE
add/load track" when pressed on empty space

### ISSUE THREAD

**Issue by aargirakis** [aargirakis/BZRPlayer#23]

**Comment by ciros88** [comment]
please can you better explain this? which empty space?

**Comment by aargirakis** [comment]
Haha I thought this was your idea? You thought clicking on an empty area in a playlist would open an addfile/foler dialog.

**Comment by ciros88** [comment]
uhm nope, I would find it inconvenient to implement this, my idea was to open the file dialog when pressing play if playlist is empty and this one has been already implemented so.. i will close the issue
