### ISSUE TITLE
[pdx] Not playable

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#231]
Found an audio format that can't be played in BZR2.

BZR's Version: 2.0.25 Alpha

Note: I'm almost sure that they r music files, bcuz some of them have names like **BGM** or **Music**.

Some samples:

[pdx.zip](https://github.com/aargirakis/BZRPlayer/files/9943677/pdx.zip)

**Comment by ciros88** [comment]
@aargirakis https://vgmrips.net/wiki/PDX_File_Format
are you interested?

**Comment by ciros88** [comment]
*.pdx files are the sharp x68000 mdx sample banks, and should be already supported by mdxmini

**Comment by ciros88** [comment]
i can confirm that pdx files are correctly handled by bzr2 thru mdxmini:
[sharp x68000 mdx & pdx.zip](https://github.com/aargirakis/BZRPlayer/files/11789291/sharp.x68000.mdx.pdx.zip)
these two mdx example tracks will play the drums only if the related pdx samples file is placed in the same directory.
