### ISSUE TITLE
[titel] Not playable

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#246]
Found an audio format that can't be played in BZR2.

BZR's Version: 2.0.25 Alpha

Note: I'm almost sure that they r music files, bcuz a lot of them located in a folder named "unsorted gamemusic".

Some samples:

[titel.zip](https://github.com/aargirakis/BZRPlayer/files/9943829/titel.zip)

**Comment by ciros88** [comment]
bzr2 can play all of them.
smpl.titel is the sample file (a bad rip) of https://www.exotica.org.uk/wiki/Crystal_Palace ... you can play smpl.titel you provided with mdat.titel from exotica

**Comment by rayman3003** [comment]
Yeap, they plays in BZR2. It was a mistake by me. :P
