### ISSUE TITLE
[dss] Not playable

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#247]
Found an audio format that can't be played in BZR2.

BZR's Version: 2.0.25 Alpha

Note: I'm not 100% sure that they r music files.

Note2 : They are located in a folder named "win32-trackers\Dream Station"

Some samples:

[dss.zip](https://github.com/aargirakis/BZRPlayer/files/9943846/dss.zip)

**Comment by ciros88** [comment]
oh cool dream station tracker, but for what i know didn't exists a lib for playing it

**Comment by aargirakis** [comment]
I think we can forget about this
https://www.youtube.com/watch?v=Cbvtzl2Pm6c&ab_channel=RonanFed
https://www.kvraudio.com/product/dreamstation-ii-by-audio-simulation

Seems as likely as playing a cubase file.
