### ISSUE TITLE
crash with m4a files (2.0.25.Alpha regression)

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#248]
before 2.0.25.Alpha m4a files (currently unsupported, as #107) was flawlessy skip (as #119)

**Comment by aargirakis** [comment]
Which one? I tried dmt.m4a in #107 and it skipped it as it should, tried 2.25, 2.26 and 2.27

**Comment by ciros88** [comment]
https://filesamples.com/formats/m4a

these m4a, apart Symphony No.6 ( see #253 ) are correctly skipped.
but i have various m4a that makes bzr2 crash, and for what i've seen, only little m4a files are correctly skipped. try it

**Comment by ciros88** [comment]
seem that monly 4a files from about 8-10mb and over have an higher probability makes bzr2 crash (im sure you will found a lot of them on your hd)

**Comment by aargirakis** [comment]
It's the MDX-plugin that tried to load the m4a-files. I'll see if I can fix it.
