### ISSUE TITLE
crash when doing tracklist -> "remove selected" action, from bottom to top, on multiple tracklist entries (subtunes or tracks)

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#254]
how to reproduce:

add a track (i've used the one attached) with subsongs, play it then stop it), delete or move the file on hd, then select two or more subtracks and click on remove selected.

[Unknown Huelsbeck.zip](https://github.com/aargirakis/BZRPlayer/files/9961602/Unknown.Huelsbeck.zip)

**Comment by aargirakis** [comment]
I did exactly like you described without any crash. And I don't think deleting or moving a physical file have any impact on BZR Player. It only check the file when it plays it.

**Comment by ciros88** [comment]
ookay..after a Lot of tries..i've found the issue!
it is not about removing subtune entries of a deleted file only: the problem is not the file itself, is how bzr2 removes subtunes .

how to reproduce:
try to open the same attached track and play it. then select the 3rd and the 2nd subtunes only and do the remove selected action: will crash
