### ISSUE TITLE
muting a channel will crash broking channels handling for subsequent instances

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#261]
oh.. not an easy one.
what happended:
i was listening a playlist, and in particular the attached track. then i muted first channel (through channel window): bzr2 crashes (1st bug).
![crash](https://user-images.githubusercontent.com/84340161/200813920-6b7a1f83-c957-488a-98c2-262b9588fcce.gif)

i've launched it again, then played the same track: now some channels are muted by default (2nd bug). the muted state doesnt appear in the channel view (3rd bug) but you can see it in the tracker view (and, obiouvsly, you can hear it):
![immagine](https://user-images.githubusercontent.com/84340161/200809093-3427e259-ba93-42d6-a6cb-a60803c8fc5c.png)

now, click on the same track for playing it again will unmute all channels. so..everything seems ok now but (yes..it isn't finished yet :smile: ), muting a channel (from the channel window) now doesnt crashes anymore but will mute more than the selected one (you can see that they are muted it in the tracker view) (4th bug). 

https://gifyu.com/image/SEUq8 (gif loading time could be a little high)

now.. (not finished yet!), unmute the just muted channel will not work: the channel will remain muted (5th bug).

so, summarizing:
- 1st bug: app crash when unmute a channel (i've tried with first one) from the channel window
- 2nd bug: restarting the app and playing the same track again will starts with already muted channels
- 3rd bug: there is no consistency between channel view infos and tracker view infos about the muted channels: channel view is wrong
- 4th bug: mute a single channel from the channels window will mute some other channels also
- 5th bug: unmuting the just muted channel (from the channels window) will have no effect

dunno if you will be able to reproduce all the 5 bugs.

also dunno how much they are related themselves

dunno if some of them are regressions

[AMIGAMIX.ZIP](https://github.com/aargirakis/BZRPlayer/files/9970036/AMIGAMIX.ZIP)

**Comment by aargirakis** [comment]
Muting a song with more than 16 channels is broken, this has to do with #104
