### ISSUE TITLE
prevent unnecessary cpu/gpu load of unselected tabs

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#265]
when tracker view and visualizer windows are docker in tabs that has not selected, their cpu/gpu load should be prevented

![immagine](https://user-images.githubusercontent.com/84340161/201465587-27ed5719-0788-45f7-9564-ccc5ec0b37d4.png)

**Comment by aargirakis** [comment]
This got fixed with the new GUI-system
