### ISSUE TITLE
rename "Window" menu to "View"

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#268]
this little refactoring makes more sense with #269

**Comment by aargirakis** [comment]
I think "Window" is more common, Adobe use that in their programs. Also Unity, Unreal Engine etc. I think "View" is more common if you just can toggle tooolbars etc. So unless you have a good reason I'm gonna go with "Window".

**Comment by ciros88** [comment]
dunno if "window" is more common, i've opened some softwares in sparse order on my pc and "view" is used in vlc, visual studio code, notepad, office, firefox, etc. many other softwares have both "view" and "window" and both of them do different things. 
i think is not a question of which is more common but, in this context, whitch seems more descriptive and adapt. at my eyes "view" seems more explicit, but if think "window" is better then close the issue :thumbsup:

**Comment by aargirakis** [comment]
Those program you mention though doesn't have windows/widgets. So I think it's mostyle like this:
windows/widgets interface = window
simpler/not so configurable = view
