### ISSUE TITLE
make uade silence detection time configurable via settings

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#274]

**Comment by ciros88** [comment]
2.0.34.Alpha:

silence detection should be able to be disabled. two different ways for doing it:

- an enable disable button. when disabled, time slider should be greyed out
- the minimum time slider value displayed is 'off' instead of '1' or even '0' ('0' isn't so clear after all)

maybe the first way is better

**Comment by aargirakis** [comment]
This is fixed. Set it to enabled/disabled in settings.
