### ISSUE TITLE
crash when clearing a playlist while a track is playing and repeat is enabled

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#275]

**Comment by aargirakis** [comment]
I don't think this is crashing any more?

**Comment by ciros88** [comment]
seems it continue to crash

**Comment by aargirakis** [comment]
It crashes when the song ends though, right?

**Comment by ciros88** [comment]
my bad, i didn't added a decent description to this issue.. yeah it tries to go on the next one but there is no a next one so it crashes.
