### ISSUE TITLE
wrong track played when multiple are selected

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#277]
how to reproduce it:
add tracks, then select some of them (or all with ctrl+a) and press enter or click on play.
i mentioned ctrl+a because it is the quicker way to see the bug: the last entry is played everytime regardeless of the 'highlighted' one. 

so when multiple tracks are selected, if there is an highlighted one it should be played instead of the last, and if there is none highlighted then the first should be played as the users expects, not the last. if none is selected and shuffle is enabled than a random track should be played

**Comment by aargirakis** [comment]
How do you mean highlighted?

I tested in Foobar or VLC I think and the behavior was the same as here = the last track is played if multiple are selected

**Comment by ciros88** [comment]
> How do you mean highlighted?

for "highlighted" i mean it has a rectangle of dots, i mean it is "clicked"
in this screen, 3 tracks are selected and foregone destruction is highlighted
![immagine](https://user-images.githubusercontent.com/84340161/206740143-86104186-b82c-4836-8d55-6d75b94fa218.png)

i know that it isn't the better word to describe it, but it is in line with the right-button selection action (eg. remove selected)

> I tested in Foobar or VLC I think and the behavior was the same as here = the last track is played if multiple are selected
what is the meaning of play the last track of a selection group? if an user want to play the last first..why he put it on the last? this is why i think vlc (and also winamp & qmmp) behave correctly

**Comment by ciros88** [comment]
2.0.34.Alpha:
if playlist has some tracks then everything works fine, but:
if the playlist is clear, when you drop some tracks then press enter or ctrl+a&enter it will crash
