### ISSUE TITLE
restore minimized to systray with minimize button is broken when it is fullscreen

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#280]
when "minimize to systray on minimize" is enabled, you can minimize to systray in two manner:
clicking on the systray icon, or click on minimize window button.
then, you can restore it clicking on the systray icon.

now if you have bzr2 opened in full screen window, and minimize it through minimize window button, then clicking on systray icons will not restore it correctly: it will be not fullscreen anymore, and visualizer will be black if inactive (as for #206 ).

**Comment by ciros88** [comment]
2.0.34.Alpha:
now it opens everytime in fullscreen window, also if the windows wasn't full screen before the minimization

**Comment by aargirakis** [comment]
Can you descibe exactly how you do? Because for me it works fine.

**Comment by ciros88** [comment]
open bzr2 and put in in fulldesktop, now toggle fulldesktop off and click on window minimize button or on taskbar icon (not systray but taskbar icon), then click on systray icon to re-open: it will open in fullscreen again

**Comment by aargirakis** [comment]
Ah OK. The bug only appears if you click minimize or taskbar icon. Great, I'll take a look.
