### ISSUE TITLE
wrong layout when launching bzr2 through external file opening

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#285]

**Comment by aargirakis** [comment]
What do you mean? I tested double clicking on a file and "open with" BZR Player 2, and the program started fine.

**Comment by aargirakis** [comment]
Ah I see now, because the exe is opened not from the current directory it loads the settings from aonther place

**Comment by ciros88** [comment]
yeah, a settings.ini should not be created in the current track dir (as it is garbage)
