### ISSUE TITLE
add midi support

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#29]

**Comment by aargirakis** [comment]
It's a strange bug in the libxmp plugin that causes loading midi to crash. If you remove the plugin it will play fine. Looking into it.

**Comment by ciros88** [comment]
now that libxmp has been dropped, how we can play midi files?

**Comment by ciros88** [comment]
could be libxmp (temporary) enabled for midi only?

**Comment by ciros88** [comment]
Adplug should already support midi playback

**Comment by aargirakis** [comment]
MIDI is played by FMOD

**Comment by ciros88** [comment]
currently midi doesn't (starting from 2.0.28.Alpha/2.0.29.Alpha)

**Comment by aargirakis** [comment]
[Holiday.zip](https://github.com/aargirakis/BZRPlayer/files/10230909/Holiday.zip)
What? This file doesn't work for you?

**Comment by ciros88** [comment]
> [Holiday.zip](https://github.com/aargirakis/BZRPlayer/files/10230909/Holiday.zip)
> What? This file doesn't work for you?

nope

**Comment by aargirakis** [comment]
Working fine for me. Still not working for you?

**Comment by aargirakis** [comment]
Do you have a gm.dls in your C:\Windows\System32\drivers ?

**Comment by ciros88** [comment]
> Do you have a gm.dls in your C:\Windows\System32\drivers ?

yes.. but midi playback is working in bzr1.

apart from this, I think bzr2 should provide an out of the box solution for midi playback like as other formats without relying to other file system or eternal files: i mean bzr2 shouldn't depend on a specific system lib but everything needed should be shipped inside the app folder (as the qt libs). What i propose is: add the gm.dls to the bzr2 folder so the user doesn't need to do any extra step, but also add a preference for been able to select another one like that in system32/drivers dir (the same bzr2 already does with songlength: the embedded one is used as default, but u can specify another one from preferences dialog). 

[gm.zip](https://github.com/aargirakis/BZRPlayer/files/10791186/gm.zip)

Then we could also talk about fmod and soundfonts support. see:

https://qa.fmod.com/t/does-fmod-support-applying-sf2-extension/14073/2
https://www.kvraudio.com/forum/viewtopic.php?t=49885
https://www.kvraudio.com/forum/viewtopic.php?t=49885

...but this is another chapter.

**Comment by aargirakis** [comment]
I actually added an option some while ago regarding exernal gm.dls. I removed it I think in version 2.0.41. Is it still not working?

**Comment by ciros88** [comment]
still not working in 2.0.43.Alpha

**Comment by ciros88** [comment]
finally now midi playback is working.. but there are still some midi files that doesn't play.
they correctly play in other players with midi support (also in openmpt)
[Tyrian Midi.zip](https://github.com/aargirakis/BZRPlayer/files/11061642/Tyrian.Midi.zip)

**Comment by aargirakis** [comment]
That's beacuse those are RIFF-based MIDI: https://www.loc.gov/preservation/digital/formats/fdd/fdd000120.shtml

**Comment by ciros88** [comment]
from 2.0.59.alpha midi stopped working
