### ISSUE TITLE
The percentage character in the pitch is slightly cut off.

### ISSUE THREAD

**Issue by Vamped-Amiga** [aargirakis/BZRPlayer#293]
The percentage character in the pitch is slightly cut off.

**Comment by aargirakis** [comment]
This is probably because, as I can see in #292 you're not using the correct font. (Roboto). I'm gonna see why it doesn't gets installed correctly. But you can probably fix this for your self by installing The Roboto fonts in /resources

**Comment by Vamped-Amiga** [comment]
I understand that this could be a solution, but shouldn't the Roboto font be installed together with the BZR Player?

**Comment by aargirakis** [comment]
Yes it should be, I'm not sure why it doesn't. So it's a bug.
