### ISSUE TITLE
Memory Leak in BZR2

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#299]
It seems that there is a "Memory Leak" bug in BZR2 (v2.0.34 Alpha):

After adding & playing more than 100 songs in the BZR2, the amount of memory that BZR2 occupies, gets increased more & more, until it reaches near the 1GB RAM!

& After reaching to 1GB, the BZR2 starts to crash, sooner or later! (I have about 10GB free ram!)

It doesn't matter which type of files is getting added to the playlist. But it seems the size of files, increase/decrease the speed of hogging the memory. for example:

If u add 100 files that each one has 5MB size, the Memory Leak will occurs sooner than adding 100 files with 500KB size. For smaller-size files, the Memory Leak occurs later. maybe after playing 200 files (& not 100 files!)

Here is a screenshot of amount of RAM that BZR2 occupied, after playing 100+ files:

![BZR1](https://user-images.githubusercontent.com/17022701/209667153-91372941-a65e-4a01-80f0-15a525be60fc.png)

This "Memory Leak" bug was available in BZR 1.0.6 too!

& I think it's a serious bug.

**Comment by ciros88** [comment]
as general rule, please update to latest version an try the issue on it before open an issue

**Comment by rayman3003** [comment]
> can u confirm the issue persists on 2.0.35.Alpha also?

I will try the bug with 2.0.35.Alpha & report back here.

**Comment by rayman3003** [comment]
OK. I tried with 2.0.35.Alpha & here is the result:

With common music formats (mp3 & ogg), this Memory Leak won't occur.

But, when I playback the chip tunes (tunes that use Tackers), the Memory Leak happens!

For example, after playbacking more than 150 *.it (Impulse Tracker) & more than 400 *.xm (FastTracker), the Memory Leak occurs & then BZR2 crashed.

It happens after BZR2 hogs 1GB or more RAM. For example, for *.xm files, BZR2 crashed, after reaching 1600 MB RAM.

Here is the screenshots I took, to show the progress of hogging memory by BZR2 (It crashed after 1.6GB):

![a](https://user-images.githubusercontent.com/17022701/210111195-74778ca7-56c2-4c3b-9a90-bbe70f97f274.jpg)
![b](https://user-images.githubusercontent.com/17022701/210111212-da414c10-8e96-445e-b879-b3aa46856500.jpg)
![c](https://user-images.githubusercontent.com/17022701/210111214-1b58946f-c16e-4f7c-b705-f10337476365.jpg)
![d](https://user-images.githubusercontent.com/17022701/210111216-4dfd7687-3b8c-4906-9e06-7b476443dfe3.jpg)
![e](https://user-images.githubusercontent.com/17022701/210111218-29d55f96-4fa7-41c4-9907-f92e222fd0dd.jpg)
![f](https://user-images.githubusercontent.com/17022701/210111220-e13a7b3b-56c5-4908-99eb-a331678c9f26.jpg)
![g](https://user-images.githubusercontent.com/17022701/210111223-5f0c4b31-8e41-4ec7-823e-ee582c29f650.jpg)
![h](https://user-images.githubusercontent.com/17022701/210111225-6a024fb6-bb82-464c-b748-4194de033244.jpg)
![i](https://user-images.githubusercontent.com/17022701/210111227-1f860d95-a3f2-44d4-bfe6-a69f189c382c.jpg)
![j](https://user-images.githubusercontent.com/17022701/210111228-823c1734-6a2d-4cc3-8cd3-ba1211b689b5.jpg)
![k](https://user-images.githubusercontent.com/17022701/210111230-7125f1a9-0aa4-43e7-84a8-ba11bc13a497.jpg)
![l](https://user-images.githubusercontent.com/17022701/210111231-f1df421d-5372-45b4-8480-3c58d046437c.jpg)
![m](https://user-images.githubusercontent.com/17022701/210111233-06cf4240-d99f-4f5e-93c8-e1e6d17cac9b.jpg)
![n](https://user-images.githubusercontent.com/17022701/210111235-c944dc14-bdeb-4e85-98eb-5835fff1b573.jpg)

**Comment by ciros88** [comment]
Really a good find! Thank u

**Comment by aargirakis** [comment]
I played about 250 files, mostly Protracker mods and after that I have 250mb memory consumption. Yes, there is still probably a memory leak but not very big. I'll see if there's any difference with it/xm.

**Comment by rayman3003** [comment]
> I played about 250 files, mostly Protracker mods and after that I have 250mb memory consumption. Yes, there is still probably a memory leak but not very big. I'll see if there's any difference with it/xm.

Yeap. The amount of Memory Leak, is different for different trackers. & also it depends on the size of files too. 

For example, bcuz mod files has smaller size, the Memory consumption is slower. & for *.it & *.xm files, the Memory consumption is faster, bcuz *.it & *.xm files has larger file sizes.

I also today tried to play more than hundreds of *.mod files (Protracker). Memory leak & crash happened, but very slowly! Maybe after playing 450 or 500 *.mod files!

**Comment by aargirakis** [comment]
Yep, I've downloaded the 200 largest it-files from modland and I can confirm that you can tell pretty fast that there's a memory leak. I will investigate.

**Comment by aargirakis** [comment]
I've fixed (most of) the leak!

**Comment by rayman3003** [comment]
> I've fixed (most of) the leak!

Thank u for bug-fixing. 👍
