### ISSUE TITLE
Hotkeys?

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#300]
It seems that the BZR2 (v2.0.34 Alpha) has different hotkeys than the BZR1 (Bczu the hotkeys of BZR1 doesn't work in BZR2).

Or maybe BZR2 doesn't have any hotkeys yet!

I think it is important to have hotkeys for all available buttons.

So please don't forget about adding hotkeys to the BZR2.

**Comment by ciros88** [comment]
see #18 , some of them has been already implemented, but there are some difficulties on it. it's a work in progress

**Comment by ciros88** [comment]
please update to 2.0.35.Alpha, in 2.0.34.Alpha hotkeys wasn't enabled

**Comment by rayman3003** [comment]
OK, thank u.

**Comment by ciros88** [comment]
as i said, there are some implementation difficulties, and for this reason the play/pause isn't actually spacebar as suggested in #18 but F5 (yeah, dont like it, it's so hard to press that distant key!) and you need to click on tracklist/playlist component before in order to get it working

**Comment by rayman3003** [comment]
OK, better than nothing.

But is there any text files that list all available hotkeys of BZR2?

**Comment by ciros88** [comment]
when bzr2 will reach a mature state i suppose a txt file will be included or an help/infos hint will be added

**Comment by rayman3003** [comment]
One more question: Whats the hotkey for the next file button?

**Comment by ciros88** [comment]
Yeah P & N hotkeys are really useful, but i haven't added them for now because of some difficulties in the implementation

**Comment by rayman3003** [comment]
Is there any progress for hotkeys?

**Comment by ciros88** [comment]
regarding status of implemented hotkeys see #18 , about how to make the user aware of them see #330
