### ISSUE TITLE
After a Next on the original playlist, we were unable to listen to a single track from the new playlist.

### ISSUE THREAD

**Issue by Vamped-Amiga** [aargirakis/BZRPlayer#302]
When we use 2 tracks in the existing playlist we do Next to listen to the second track and everything is ok, but accessing the only track in the new playlist, BZR Player crashes.

**Comment by ciros88** [comment]
I have not been able to replicate this scenario with 2.0.36.Alpha for compare with 2.0.37.Alpha in order to mark the issue as closed or not. @Vamped-Amiga please can you better explain me all the actions i need to do in order to replicate it?

**Comment by aargirakis** [comment]
If I remember correctly the crash occured when:
You have a playlist with some songs (I think you have to play one of them)
Then you create a new playlist and add a track to that. Play that file and the crash occurs.

**Comment by ciros88** [comment]
yeah, so i can confirm that this behaviour has been fixed
