### ISSUE TITLE
crash while deleting a currently listening track (2.0.36 regression), and then crash while tying to play any file until settings.ini is removed

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#310]
i was using bzr2 and, after a certain number of actions, i've removed a track entry (a sid subtune) that i was currently listening from a specific playlist (not the default one) and bzr2 crashed. after this event, every time i launched brz2 and tried to play any track it immediately crash. only by deleting settings.ini it returned to work correctly. i've attached the faulty settings.ini

[settings.zip](https://github.com/aargirakis/BZRPlayer/files/10474137/settings.zip)

**Comment by aargirakis** [comment]
I know there is a bug with this setting:
currentRow=123
Try to remove that and see if it works

**Comment by ciros88** [comment]
yeah, i can confirm that deleting the currentRow now playback has been restored. so they are 2 different bugs:
 - crash when removing a playing track entry
 - currentRow failure

**Comment by ciros88** [comment]
the two bugs still persists if the operations are made with having two different playlists. i mean: with one playlist only (default.m3u) now it works and also providing the buggy settings.ini is correctly handled. bug having default.m3u and another m3u, and acting on this last one (delete a currently play track on this) it crashes, and then also the currentRow failure seems to happen (dunno if it is caused really by the currentRow but it behaves as described in the first comment, no other tracks will play anymore until settings.ini is removed)

**Comment by ciros88** [comment]
2.0.38.Alpha: the crahs while remove a plying track seem solved only for some scenarios, but still crashes if i simply open bzr2, add a track, play it then remove it from tracklist. it still persist removing currentRow from settings.ini

**Comment by ciros88** [comment]
2.0.43.Alpha: the crash still persists. steps to reproduce it: download 2.0.43.Alpha, open it and drop a track, play it then remove it.

**Comment by ciros88** [comment]
> 2.0.43.Alpha: the crash still persists. steps to reproduce it: download 2.0.43.Alpha, open it and drop a track, play it then remove it. also deleting a playlist that contain a currently played track makes bzr2 crash

2.0.55.Alpha:
deleting a playlist that contain a currently played track still makes bzr2 crash
