### ISSUE TITLE
add utf8 support for playlists

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#315]
this is an example of playlist with unhandled utf8 chars
[Coding - Rayman.zip](https://github.com/aargirakis/BZRPlayer/files/10610493/Coding.-.Rayman.zip)

**Comment by ciros88** [comment]
if this playlist is dropped into bzr2 it is incorrectly displayed but the tracks playing fine. however, if the playlist is copied into bzr2 "playlists" directory then the tracks won't play

**Comment by aargirakis** [comment]
This has nothing to do with playlist. It's bad encoding read from the ID3 tags. It's the same with Swedish lettes åäö.

**Comment by aargirakis** [comment]
Actually I was wrong, it was latin1 with special characters that didn't work. Working now.
