### ISSUE TITLE
Display sid subsongs in playlist

### ISSUE THREAD

**Issue by aargirakis** [aargirakis/BZRPlayer#32]

**Comment by ciros88** [comment]
zxtune supports it... but it is a little bit annoying in my opinion. I think the best way to implement it is by adding a triangle to the right of track name in playlist, unexpanded by default. when clicked, it will expand the track showing all its nested (graphically indented) subsongs

**Comment by ciros88** [comment]
also could be useful to add a preference for choosing to play all subsongs or the first/default one only

**Comment by ciros88** [comment]
add possibility to remove from playlist both entire sid or individual subsongs. this means:
- selecting the main entry (those with the triangle) the remove action should remove entire sid from playlist.
- selecting one or more subsongs, the remove action should remove that subsongs only

**Comment by ciros88** [comment]
add possibility to move them detaching from parent sid (this need #69 first)

**Comment by ciros88** [comment]
add visual feedback to fix previous/next subsong buttons (like already happens with previous/next track buttons)

**Comment by ciros88** [comment]
consider the possibility to add an options for wrapping around last subsong to first subsong with "next subsong" action or viceversa with "previous subsong" action

**Comment by ciros88** [comment]
"loop one" sid button:
consider the possibility to add a button for loop all subsongs of entire sid.
the actual "loop one" button on a subsong will loop only the currently played subsong, not the entire sid
button could be added near "next/previous subsong" or as another choice in addition to "loop none" "loop all" "loop one"
