### ISSUE TITLE
restyle/remove the "new playlist" button

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#322]
personally i don't like too much the "new playlist" button as it is too big (for an aesthetical perspective but also because it occupy too much space on the screen that could be used for other elements) and white (this doesnt mixes well with the overall theme)

what do you think about one of these 2 proposals:

1. reduce it as a circle with a '+' sign inside, with the same style of the play button (or something similar, smaller and shorter then the actual "new playlist" button)
2. remove it and add the 'new' action on rightmouse button in the playlists window (that appears only when menu is opened in empty space and not on an entry) (this in my opinion could be added regardless of proposal 1)

**Comment by aargirakis** [comment]
I think something like this look good: (Photoshop)
![Untitled-2](https://user-images.githubusercontent.com/10993634/220209670-456101e2-9c2c-4266-83e3-080707382c6c.png)

**Comment by ciros88** [comment]
this looks definitely better and resolve the aesthetic issue, but it continues to occupy a space that could be user for something else. you know, having so much windows on the app we should save as much space as possible. this is why i've proposed to remove it and add a rightbutton entry for doing it. also, im thinking about moving the circle with the plus sign next to the "playlists" window title text. do u think it is possible? it could save space without sacrify this symbol

**Comment by aargirakis** [comment]
There is a possibility of adding a menu in all the tab menus where "new playlist" could be. But I'm not a big fan of hiding everything, The more you hide the harder the user has to understand the program. And it's not occupying THAT much space...

**Comment by ciros88** [comment]
> I think something like this look good: (Photoshop) ![Untitled-2](https://user-images.githubusercontent.com/10993634/220209670-456101e2-9c2c-4266-83e3-080707382c6c.png)

like it: for me it's GO
