### ISSUE TITLE
weird behaviour with ahx (2.0.42.Alpha regression)

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#338]
now some tracks arent playable anymore, and other plays but with strikethrough text

[ahx.zip](https://github.com/aargirakis/BZRPlayer/files/10824678/ahx.zip)

with 2.0.41.Alpha all these tracks was playing fine and without strikethrough text

**Comment by aargirakis** [comment]
Definatley has to do with #328

**Comment by aargirakis** [comment]
Should be fixed now
