### ISSUE TITLE
When closing settings, a playing sound shouldn't stop if you didn't change the sound output

### ISSUE THREAD

**Issue by aargirakis** [aargirakis/BZRPlayer#339]

**Comment by ciros88** [comment]
Ive didnt opened this before because i tought wasnt really necessary at this time, but yeah if u, for example, play a track when open preferences, enable millisecs closing preferences window the current track stops. With other preferences it crashes also, happened often

**Comment by aargirakis** [comment]
With other preferences? What do you mean?

**Comment by ciros88** [comment]
there are some other preferences that crash bzr2 in the same scenario. happened various times, now dont remember which. if happens again i will report it
