### ISSUE TITLE
sample loop not triggered (drums) in Prorunner 2.0 (libxmp)

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#34]
[pru2.zip](https://github.com/aargirakis/BZRPlayer/files/8875687/pru2.zip)

**Comment by aargirakis** [comment]
libxmp bug. Works fine in UADE

**Comment by ciros88** [comment]
closed as libxmp has been removed: now it is correctly played by uade

**Comment by ciros88** [comment]
2.0.35.Alpha regression

**Comment by aargirakis** [comment]
@ciros88  I think this can be closed now. Sounds fine in 2.0.56.
