### ISSUE TITLE
Customizable time of left/right arrow

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#340]
Currently, when using the arrow keys of keyboard (left & right), the song moves 10 seconds back or forward.

If it could be possible to add an option in settings, so the user could change this 10 seconds, to any preferable time that s/he wanted, it would be awesome. [For example from 1 second to 30 seconds!]

If not possible, please change the 10 seconds to 5 seconds. Bcuz IMO, 5 seconds is more reasonable than 10 seconds, for this purpose.

**Comment by ciros88** [comment]
something like this has been already implemented in the vlc style: see #18 
what is missing is a dialog that shows all the shortcuts #330

**Comment by rayman3003** [comment]
> something like this has been already implemented in the vlc style: see https://github.com/aargirakis/BZRPlayer/issues/18

That one there, is not customizable. It only about some pre-defined seconds (3-5-10-60 seconds)

Customizable is better. I mean an option in the settings that can be changed from 1 to 60 seconds. (1-2-3-4-5-6-...-60 seconds)

**Comment by rayman3003** [comment]
> u can have multiple time ranges at the same time, not only one.

Yeah; But is it really necessary to have multiple time ranges at the same time? 🤔 Does anybody need that? I don't know! ¯\▁(◔◡◔)▁/¯

Anyhow, Having a 5 seconds (for any of those hotkeys), is enough for me. 😄

**Comment by ciros88** [comment]
Speaking for myself, yeah u often use different ranges (when u know this shortcuts exists you start using them). But i think im not alone (probably this is why it has been implemented in a big project like vlc).

**Comment by rayman3003** [comment]
> Speaking for myself, yeah i often use different time ranges

OK, In that case. Lets have multis! 🤩

 But I hope the main hotkeys [left & right directional keys on keyboard <- & ->] became 5 seconds. 😜

**Comment by ciros88** [comment]
depends of the size of the tracks u use normally. 10secs seems a good default choice for handling 3 to 30 minutes tracks (i suppose this is why vlc choose it)

**Comment by rayman3003** [comment]
> 30 minutes tracks

30 minutes tracks? R u kidding me? 🤣

Most tracks are between 3 to 5 minutes.

& for this range, 5 seconds is better.

Also, bcuz so many times, I listen to game musics, & bcuz most games musics are between 40 seconds to 2 minutes; a 5 seconds is better for these too.

> this is why vlc choose it

I don't why u always refer to vlc?! I know that vlc can play some audio files; but vlc is mostly a video player. So if they choose 10 seconds for it, is bcuz 10 seconds is suitable for a 90 minutes movie! ¯\▁(◔◡◔)▁/¯

**Comment by ciros88** [comment]
Vlc is actually one of the most used/popular media player for music and videos, its a de facto standard. Not the only one, but very useful for taking ideas and inspirations, probably thanks to its excellent usability. About music duration can be vary, please not reduce it to max 5min  "canonical" length.

**Comment by rayman3003** [comment]
In which version of BZR2 this feature added?

bcuz I tried the 2.0.74, & couldn't find it anywhere.
