### ISSUE TITLE
Add support for USF (N64)

### ISSUE THREAD

**Issue by aargirakis** [aargirakis/BZRPlayer#345]
Look here:
https://github.com/saschaklick/audacious-usf-plugin
https://www.foobar2000.org/components/view/foo_input_usf

**Comment by ciros88** [comment]
support for Ultra64 Sound Format (USF) would be Lovely!
there is a pretty old (but good i suppose) library for playing usf:
https://github.com/kode54/lazyusf
this seems an updated fork:
https://github.com/derselbst/lazyusf

a couple of players using lazyusf (dunno if the old or new one):
https://github.com/jprjr/VGMPD
https://github.com/derselbst/ANMP
