### ISSUE TITLE
icon on Windows Tiles doesn't fit

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#350]
icons.png (in resources dir) and VisualElementsManifest xml (in root dir) file are missing.
[BZRPlayer.VisualElementsManifest.zip](https://github.com/aargirakis/BZRPlayer/files/11039430/BZRPlayer.VisualElementsManifest.zip)

with:

![immagine](https://user-images.githubusercontent.com/84340161/226890739-bc042b5c-5e3c-4f98-a7f4-266eb6932cb2.png)

without:

![immagine](https://user-images.githubusercontent.com/84340161/226890649-14dcf3f9-5105-428d-9ce8-b86617ddc492.png)

**Comment by ciros88** [comment]
I took it from 2.0.22.Alpha .. it wasnt in that release?

**Comment by ciros88** [comment]
Oh sorry, that file was mine. But yeah, just put it into root end the icon will fit the tile

**Comment by ciros88** [comment]
2.0.46.alpha:
now icon returned.
@aargirakis: do u think also the VisualElementsManifest (needed for best icon fit) will be added?

**Comment by aargirakis** [comment]
I've never used or heard of that file. Is that "Windows Tiles" a windows 11 feature? I've you know how to create that file give it to me and I'll include it in the next version.

**Comment by ciros88** [comment]
Tiles are the icon of start menu starting from win8. The attached file is already ready to be placed in bzr2 root. Try it

**Comment by aargirakis** [comment]
OK and how do I see it?
