### ISSUE TITLE
bzr doesn't start with enqueueitems=true && AllowOnlyOneInstance=false

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#356]
it shouldn't be possible to enable items enqueue if one instance mode is disabled (should be greyed out)
if happens, bzr2 won't start anymore. moreover, also blocking this possibility from the GUI, at settings.ini bzr2 should only consider enqueueitems value only if AllowOnlyOneInstance is true, or consider it's default value (that is enqueueitems=false) implicitly if AllowOnlyOneInstance is false. this will prevent bzr2 from crashing.

**Comment by aargirakis** [comment]
Seems like it's enough to use AllowOnlyOneInstance=false for BZR to not start, right?

**Comment by ciros88** [comment]
Yeah i've noticed this in these days with more recent versions, but if i well remember, when i've added this issue (on march) AllowOnlyOneInstance=false && enqueueitems=false was working (don't remember which version i have used)

**Comment by ciros88** [comment]
im going to close the issue since it has been fixed, but i suggest to grey out also the enqueueitems switch (not only the text) as happens with the reverb or normalize switches when they are disabled
