### ISSUE TITLE
Possibility to save and restore the windows arrangement before quitting

### ISSUE THREAD

**Issue by Vamped-Amiga** [aargirakis/BZRPlayer#365]
Possibility to save or restore various window arrangements, before quitting the BZR Player. This way we don't lose the window arrangement when the player crashes, and we can have several window arrangements according to the formats we are playing.

![imagem](https://user-images.githubusercontent.com/120969460/227746550-5b4ce7b0-af88-469f-b6d5-62dfe187052e.png)

**Comment by ciros88** [comment]
#366 is a reduced version for single workspace arrangement save
