### ISSUE TITLE
Reduce default width of 'subsong' column

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#376]
realistically, the bigger value that could be displayed inside is a number which its number of digits is less than the number of column name chars (9999999 value -> 7 chars), so the default width should be, at least, equal (or smaller) than the column title width itself.
having this, will help to reduce the overall columns width, having more room for columns like 'title' without necessarily making the bottom scroll bar appear

current behaviour:
![immagine](https://user-images.githubusercontent.com/84340161/227860944-67b45cc9-92aa-41e9-adf3-083c5e21f305.png)

desidered behaviour:
![immagine](https://user-images.githubusercontent.com/84340161/227861232-e7d29440-b0bc-403e-a010-e63b2c2e274b.png)

**Comment by ciros88** [comment]
2.0.48.Alpha: the default width of 'subsong' column seem the same

**Comment by aargirakis** [comment]
![Untitled-1](https://user-images.githubusercontent.com/10993634/229599980-5547c7b4-1cdb-4063-a4ed-1ba36022a57b.png)
Maybe you have a playlist with a name that had previous old settings saved

**Comment by ciros88** [comment]
to reproduce it:
open a fresh (just installed) bzr2, drop a track (tried also with Compilation_III.sid), play it, and appears:

![immagine](https://user-images.githubusercontent.com/84340161/229711259-017b725f-ab34-4ef5-b8c5-b962b899999f.png)

also: create a new playlist, then drop the track inside it then play:
![immagine](https://user-images.githubusercontent.com/84340161/229711389-0846526c-d0e5-4fdc-9780-71c2a55a0597.png)

in first pic the width is too much, in the second pic the width is too shrinked (smaller than the SUBSONG text)

**Comment by aargirakis** [comment]
Ah ok, will take a look.

**Comment by ciros88** [comment]
persists in 2.0.51.Alpha:
both 'LENGTH' and 'SUBSONG' texts has last letters cutted.
also i've noticed that columns text is normal in default playlist but became BOLD in new playlist

![image](https://user-images.githubusercontent.com/84340161/235302213-b2a869db-6187-4bf7-bf80-5640cfff1a8e.png)

![image](https://user-images.githubusercontent.com/84340161/235302219-d5aca74d-06ef-4ad4-aefc-a9fd48f6963e.png)

**Comment by aargirakis** [comment]
OK, I will take a look again, but I think the issue mostly is that you don't have the font "Roboto" installed?

**Comment by ciros88** [comment]
I have simply unzipped bzr2 and launched it, without install nothing before

**Comment by ciros88** [comment]
the two bugs (column width and bold issue) appears on windows also (where the roboto font is installed and correctly rendered) as you can see here:

![immagine](https://user-images.githubusercontent.com/84340161/235338257-e858749d-24e5-4cd9-948c-ddb0f3ed8bd9.png)

![immagine](https://user-images.githubusercontent.com/84340161/235338267-2a55bf26-be13-4ffd-a8d8-66864beff572.png)

**Comment by aargirakis** [comment]
I agree, but it's because of issue #296 that this maybe isn't working for you. It also looks like you have other size on your menubar than mine, did you change to bigger fonts in Windows settings?

**Comment by ciros88** [comment]
Yeah i changed dpi (from 96 to 120) because at 3440x1440 resolution the text is too little

**Comment by aargirakis** [comment]
Well, that's the problem :)

**Comment by ciros88** [comment]
Uhm seems i have the same problem with 96dpi (default) also

**Comment by aargirakis** [comment]
Yes, if you change dpi in Windows hell breaks loose, that's expected.

**Comment by ciros88** [comment]
I have changed dpi from 96 to 120 in wine only, in Windows instead i havent touched it

**Comment by aargirakis** [comment]
So is this still an issue?

**Comment by ciros88** [comment]
2.0.60.alpha:
- TITLE, TYPE, LENGTH & SUBSONG texts become bold when clicking on a tracklist entry
- in wine at default dpi LENGTH & SUBSONG text now have the correct width. but increasing dpi will break it. i think most people have resolutions starting from 1920x1080, with higher dpi because of text is too little. i think it could be useful to support it

**Comment by aargirakis** [comment]
I have 1920x1080 in Windows and where you can change "The size of text, apps, and other items" it says "100% (Recommended" probably because it's a pain in the ass to support different font sizes, button sizes etc. It's a really big thing.

**Comment by ciros88** [comment]
What i mean with "support" is not a dynamic size adapatation but simpy a static one. My idea is: put ur windows to 120 or 140 (125% or 150%), see where the text overlaps or it is cutted then fix it.

**Comment by aargirakis** [comment]
Yes, but that's the thing. Then I will have to increase padding/margins/whitespace which will mean more waste of space when you use 100%.

**Comment by ciros88** [comment]
It is possibile then to get the current screen dpi and choose the increase (of padding/margins/whitespace) based on it with static values?

**Comment by ciros88** [comment]
will be closed since we can mitigate the problem with #368 and #469
