### ISSUE TITLE
tracklist entries behaviour with long names

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#378]
![bug](https://user-images.githubusercontent.com/84340161/227867762-73d5b484-ad1f-491f-95c2-7205b62ef7ec.gif)

i dont know how to reproduced it (i've used to play this playlist lot of times without any issue), but i think this behaviour is caused by long m3u track names:
[Coding - Raggae.zip](https://github.com/aargirakis/BZRPlayer/files/11075729/Coding.-.Raggae.zip)

i remember that just before having this issue i've changed main e main hover colors (while opening #377 issue) then restarted bzr2 and played this playlist

current settings:
[settings.zip](https://github.com/aargirakis/BZRPlayer/files/11075669/settings.zip)

**Comment by aargirakis** [comment]
Confirmed. It's because you have set a vergy large first column size. When the row gets selected the first column in centered hence this behavior. I'll take a look of it's fixable.
