### ISSUE TITLE
remap visualizer missing chars

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#380]
an example:
[Compilation_III.zip](https://github.com/aargirakis/BZRPlayer/files/11124383/Compilation_III.zip)

**Comment by aargirakis** [comment]
Not gonna happen. The font has a certain set of letters, if it a letter in the text isn't in the font we put a blank in. To support this example someone has to create a ü for -probably- all bitmap fonts.

**Comment by ciros88** [comment]
try to adapt these in a retrocomputer fashion (isn't a complete list):

Á À Ā Ă Å á à ā å -> A
ß -> B
Ç -> C
Ð -> D 
Ë É È è é ê ë -> E
Æ æ -> AE
ƒ -> F
Í Ì Î Ï ì í î ï -> I
Ñ ñ -> N
Ø Ó Ò Ô Õ ò ó ô ð ø -> O
Û Ù Ú ù ú ü û µ -> U
× -> X
Ý ý -> Y
¿ -> ?
¡ -> !
¯ ─ ~ · -> -
═ ‗ -> =
` ´ ‘ ’ “ ” -> ' (or " it not present)
¹ -> 1
² -> 2
³ -> 3
½ -> 1/2
¼ -> 1/4
¾ -> 3/4
½ -> 1/2
½ -> 1/2

**Comment by ciros88** [comment]
also i found this very useful: 
https://onlineunicodetools.com/normalize-unicode-text

**Comment by GugaMaster** [comment]
Implementing UTF-8 encoding should suffice:
https://www.fileformat.info/info/charset/UTF-8/list.htm

**Comment by Vamped-Amiga** [comment]
Implementing UTF-8 encoding should suffice:
https://www.fileformat.info/info/charset/UTF-8/list.htm

**Comment by ciros88** [comment]
> Implementing UTF-8 encoding should suffice: https://www.fileformat.info/info/charset/UTF-8/list.htm

the problem here is about missing gfx from font set. so the proposed solution is to fallback to existing one, following the above mentioned mapping list

**Comment by aargirakis** [comment]
I'm closing this, it won't get better than the current implementation.
