### ISSUE TITLE
unhandled whitespace in id3 tag

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#390]
id3.copyright field of the attached mp3 is "© 1995 PushButton Labs" but it is rendered in bzr2 (and also bzr1) with unknown char as first whitespace. i've copied it directly from the binary and pasted here: https://qaz.wtf/u/show.cgi and seems a normal ascii 0x20 whitespace. in fact, other software (players or id3 tag editors) handle it correctly

[TIM3_06_progressive.zip](https://github.com/aargirakis/BZRPlayer/files/11201751/TIM3_06_progressive.zip)

**Comment by aargirakis** [comment]
It's the "©" that's not rendered correctly. I added "Copyright ©" manually before the copyright data but I removed that now. I'll try to fix that ©-character.
