### ISSUE TITLE
Playing a mod file and then playing a med file, causes graphic corruption in the tracker view.

### ISSUE THREAD

**Issue by Vamped-Amiga** [aargirakis/BZRPlayer#397]
![imagem](https://user-images.githubusercontent.com/120969460/233856843-c307dfd5-e869-41d5-a84b-a92e7f3b1a7a.png)
Playing a mod file and then playing a med file, causes this graphic corruption in the tracker view, when it's relatively small.
This doesn't happen in full screen mode.

**Comment by aargirakis** [comment]
@Vamped-Amiga Hmm, can't reproduce it. Can you reproduce it and describe exactly what you did?

**Comment by aargirakis** [comment]
Sorry, now I can reproduce it.

**Comment by Vamped-Amiga** [comment]
> @Vamped-Amiga Hmm, can't reproduce it. Can you reproduce it and describe exactly what you did?

https://www.veed.io/view/11776922-7234-41c3-8e45-763f217e5f69?panel=share
