### ISSUE TITLE
crash while trying to play last subtunes of cust files (regression)

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#399]
i didn't found which version starts to have this regression (because sometimes it works and sometimes not for a single version), but seems 2.0.35.Alpha doesn't have this regression

in super Hang-On ingame cust the last two subsongs makes bzr2 crash (they plays flawlessly in deliplayer)
[cust ingame.zip](https://github.com/aargirakis/BZRPlayer/files/11309022/cust.ingame.zip)

dunno if it is related to #398

**Comment by aargirakis** [comment]
Fixed, had do do with a bug in UADE songlength file
