### ISSUE TITLE
Tracker view bugged background color when visualizer is opened (2.0.51.Alpha regression)

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#401]
happens with *.med and *.it (maybe also on other formats)

![bug](https://user-images.githubusercontent.com/84340161/235337273-1bc7b170-feca-429f-bec5-4e2f5a478ea3.gif)

**Comment by aargirakis** [comment]
Must be Wine only. Can't reproduce it on Windows.

**Comment by ciros88** [comment]
Yeah its wine only: i will try to fix it
