### ISSUE TITLE
command line multiple args are broken when bzr2 is already run

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#402]
when bzr2 is already open, run it from the command line with two tracks that contains white spaces as arguments :

-  sometimes all tracks are added to the playlist, other times only the last one (seems depends of white spaces contained in the first arg)
-  the last added is broken (entry added as unplayable)

tried with one instance mode enabled only (because of #356 )

this scenario can be reproduced also thru the windows context menu "open with" entry

**Comment by aargirakis** [comment]
Yes this is a bug. I'm looking at it, fixed some of it, some more fixing to be done.
