### ISSUE TITLE
playing track entry color become white when selected

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#408]
it should continue to be highlighted, while maintaining its currently foreground (blue) color

**Comment by aargirakis** [comment]
Don't understand, can you show a screenshot?

**Comment by ciros88** [comment]
oh man..dunno how to reproduce it O,o a combination of multiple factors triggered this issue i suppose. in any case with ur playlist refactor the game has been changed for sure, so i will close it
