### ISSUE TITLE
MilkDrop 2 Support

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#411]
MilkDrop 2 is a music visualizer that allows unlimited types of GFX to be synced with music. It was originally made for Winamp audio player. & also available as a opensource project in sourceforge. (Some other audio & video players also support it.)

https://sourceforge.net/projects/milkdrop2/

Users can make their own visualizations for this visualizer, & now we have at least 100,000+ visualizations available for download!

So I thinks it's gonna be cool that BZR2 support this good-looking visualizer. It makes the BZR2 more mature.

& Here is a collection of 42K+ presets for milkdrop:

https://archive.org/details/milkdrops?&sort=-week&page=2

![i0yadzrko19z8z3udwl2](https://github.com/aargirakis/BZRPlayer/assets/17022701/5b7a93cc-7004-4ed9-bc47-59d5b73a7a54)

**Comment by ciros88** [comment]
Seems quite old (last release from 2016)

**Comment by rayman3003** [comment]
> Seems quite old (last release from 2016)

So whats the problem of being old? 🤔

It is still working! & new presets are still coming.

-------

Aslo there is a new v3 of it available at github:

https://github.com/milkdrop2077/MilkDrop3

**Comment by rayman3003** [comment]
OK. I tried MilkDrop3 with BZR2, & it seems that MilkDrop3 works standalone, with any audio player.

So it is not necessary to include it in BZR2.

It works for all.

Please close this issue. Thank u.
