### ISSUE TITLE
these track titles make theme not playable

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#426]
these tracks in gz files has been taken from AMP website:

[MOD.happy ending .gz](https://github.com/aargirakis/BZRPlayer/files/12319086/MOD.happy.ending.gz)
[MOD.rap shit....gz](https://github.com/aargirakis/BZRPlayer/files/12319087/MOD.rap.shit.gz)
[MOD.too bad....gz](https://github.com/aargirakis/BZRPlayer/files/12319088/MOD.too.bad.gz)
[MOD.tunnetko_sykkeen .gz](https://github.com/aargirakis/BZRPlayer/files/12319089/MOD.tunnetko_sykkeen.gz)

- 'MOD.happy ending?' & 'MOD.tunnetko_sykkeen?' : play only if you remove quotation marks
- 'MOD.rap shit..' & 'MOD.too bad..' : play only if you remove the trailing dots or rename them as *.mod

i suppose these cases should be correctly handled in order to be able to play tracks as is without need to rename them

**Comment by aargirakis** [comment]
How do you even unzip a file and keep a questionmark in the filename on windows?

**Comment by ciros88** [comment]
oh damn ntfs, forgot it xD
what about the other 2?

**Comment by aargirakis** [comment]
Same thing, you can't have trailing periods in a filename on Windows
