### ISSUE TITLE
some infos disappears when removing a playing track (regression)

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#431]
'filename', 'path', 'size', 'last modified' & 'created' fields will be cleared when removing a playing track

**Comment by aargirakis** [comment]
Can't reproduce. Works fine when I play a song, remove it from playlist. Still shows all info.

**Comment by ciros88** [comment]
uhm yeah.. seems happens only when there is a single track in the tracklist

**Comment by ciros88** [comment]
> Works fine when I play a song, remove it from playlist

not playlist but tracklist

**Comment by aargirakis** [comment]
Yes, seems to bug when there is only one file in the playlist

**Comment by aargirakis** [comment]
This should now be fixed since 2.0.60.
