### ISSUE TITLE
Custom scrolltext for visualizer

### ISSUE THREAD

**Issue by aargirakis** [aargirakis/BZRPlayer#435]
Have the option to add a custom scrolltext (for all music) instead of show samples, comments text etc.

**Comment by ciros88** [comment]
i think it is not working as expected: enabling it, with custom 'test' text will makes the visualizer prints random stuff after the selected text

**Comment by aargirakis** [comment]
That is actually a separate bug, laos happens for regular scrolltexts. I'm guessing it's some random crap from memory that's printed. So should be a new issue.
