### ISSUE TITLE
playback should start from first track when clicking on "next" after adding entries to empty tracklist

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#459]
this should happens only when bzr2 playback has already started, not when it is fresh launched

**Comment by aargirakis** [comment]
Can you describe it more?

**Comment by ciros88** [comment]
the behavior when bzr2 is just fresh started is correctly: prev e next actions do nothing as expected.
but having this scenario:

- add 4 tracks
- play the 3rd
- while playing, then remove all
- re-add all
- click on next

here the expected behavior is bzr2 should play the first track, but currently it goes to the second, i suppose because starts counting from the first but it should counting from the 0 instead, i mean, it should do the same as when adding tracks for first time
instead, the "previous" action is working as intended, because it goes to the last entry, wrapping around correctly.

**Comment by aargirakis** [comment]
Also, with the exact scenario as mentioned above but shuffle is enabled it will just stop when playing next.

**Comment by ciros88** [comment]
same issue when removing a playing track then click on next: it skips the next one and plays the one after that
