### ISSUE TITLE
uncorred behaviour while playing a previous invalid track

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#462]
add a track with sub tunes, then play it. now move file in another place and play it again. all the entires are corectly greyed out. now move the file again in the origina place and play:  the track and its subtunes remains greyed out. if you do the same with multiple track then only the sub tunes remains greyed out but the first subtune is correctly rendered as sane

**Comment by aargirakis** [comment]
It has nothing to do with subsongs. The bug is:  once a file is marked as "unplayable" it will have that unplayable-opacity regardless of being playable the next time.
