### ISSUE TITLE
garbage in "artist" column when track filename contains comma char

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#474]
how to reproduce:
add a track with comma char in filename (no need to play it), then restart bzr2:
"artist" column will display "[loopcount]" text

might be related to #422 

example tracks:
[tracks.zip](https://github.com/aargirakis/BZRPlayer/files/13113469/tracks.zip)

**Comment by aargirakis** [comment]
This is a duplicate of #422 and it is not fixed.
