### ISSUE TITLE
Crashes when shuffle is enabled with new playlist

### ISSUE THREAD

**Issue by aargirakis** [aargirakis/BZRPlayer#488]
To reproduce:
1. Have shuffle enabled
2. Create a new playlist
3. Add some files
4. Play
5. Program will crash

**Comment by aargirakis** [comment]
Well, now in 2.0.62 (internal 2.0.63) I can't reproduce it. How about you @ciros88 ?

**Comment by ciros88** [comment]
tried with 2.0.60.Alpha, 2.0.61 and 2.0.62 but can't reproduce it too. 
i suppose the steps are wrong or what triggered u the crash was due a different reason
