### ISSUE TITLE
some playlists are not playable anymore (2.0.62 regression)

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#492]
but their tracks successfully play individually
[playlists.zip](https://github.com/aargirakis/BZRPlayer/files/13276655/playlists.zip)

**Comment by ciros88** [comment]
in this playlist
[playlist.zip](https://github.com/aargirakis/BZRPlayer/files/13276842/playlist.zip)
tracks accessing amiga stuff thru "Amiga%20%26%20C64%2C%20VG%20%26%20Demoscene%20Music" still works
tracks accessing amiga stuff thru "Amiga & C64, VG & Demoscene Music" not working anymore

**Comment by aargirakis** [comment]
It has something to do with encoding and some libraries work, mp3 and mods for example. I don't think there is any difference by loading a track directly or using a playlist though? You can try renaming a file that UADE can by adding a 'ä'.

**Comment by aargirakis** [comment]
Yes, it's the libraries that needs a filename as input that fails. The others support loading a file from a bytearray (with means utf8 support etc.) I'll take a look. Did you test in what version this bug was introduced?

**Comment by ciros88** [comment]
so the problem seems not about encoding but breaking compatibility with <2.0.61.alpha playlists. if u agree u can close this ticket since we are in alpha stage we don't need to maintain backward compatibility
