### ISSUE TITLE
Files with extended ascii characters in filename are not playable for plugins that doesn't support utf-8 (2.0.60 regression)

### ISSUE THREAD

**Issue by aargirakis** [aargirakis/BZRPlayer#493]
[file.zip](https://github.com/aargirakis/BZRPlayer/files/13339933/file.zip)

**Comment by aargirakis** [comment]
Try renaming a file that UADE can by adding a 'ä'. Loading will fail. It's the libraries that needs a filename as input that fails. The others support loading a file from a bytearray (with means utf8 support etc.)

**Comment by ciros88** [comment]
2.0.63:
now playing and visualizer still don't handle it
![image](https://github.com/aargirakis/BZRPlayer/assets/84340161/b6b172f4-2584-4214-a2bb-1c773c4bde4a)
