### ISSUE TITLE
furnace bugs

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#517]
this makes bzr2 crash: 'empty_PV-1000.fur'

this is recognized by fmod as mpeg: 'iji_tor_segaxboard.fur'

this is recognized by uade as onEscapee: 'one.fur'

all of them are demo tracks shipped with furnace
[furnace.zip](https://github.com/aargirakis/BZRPlayer/files/15043902/furnace.zip)

**Comment by ciros88** [comment]
2.0.71:
'empty_PV-1000.fur' still crash

**Comment by ciros88** [comment]
this one doesn't play:
[biffy_bifurcator.fur.gz](https://github.com/aargirakis/BZRPlayer/files/15263573/biffy_bifurcator.fur.gz)

**Comment by aargirakis** [comment]
> this one doesn't play: [biffy_bifurcator.fur.gz](https://github.com/aargirakis/BZRPlayer/files/15263573/biffy_bifurcator.fur.gz)

Requires Furnace 0.6.3. BZR uses 0.6.2 at the moment.

**Comment by aargirakis** [comment]
> this one doesn't play: [biffy_bifurcator.fur.gz](https://github.com/aargirakis/BZRPlayer/files/15263573/biffy_bifurcator.fur.gz)

Works now.

**Comment by ciros88** [comment]
2.0.72:
this now works:
https://github.com/aargirakis/BZRPlayer/files/15263573/biffy_bifurcator.fur.gz

but empty_PV-1000.fur still makes bzr2 crash:
https://github.com/aargirakis/BZRPlayer/files/15043902/furnace.zip

**Comment by ciros88** [comment]
still crash here

**Comment by ciros88** [comment]
> empty_PV-1000.fur from https://github.com/aargirakis/BZRPlayer/files/15043902/furnace.zip still crash here, with wine only ![image](https://private-user-images.githubusercontent.com/84340161/378728065-615cd062-80b1-42c6-8c01-40e683320684.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1Mjg4MjEsIm5iZiI6MTczNDUyODUyMSwicGF0aCI6Ii84NDM0MDE2MS8zNzg3MjgwNjUtNjE1Y2QwNjItODBiMS00MmM2LThjMDEtNDBlNjgzMzIwNjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDEzMjg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYzcxZTk4NzY0ODRmNWI1Yjc1ZTk4MmZiODI5MGE5YjQ4NWEyMmVmYTM1MDA0N2I2YzExMzZiYjg2YjRhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y8EMBtUfS1D9oKLGU4oe93hewQV1GJfDOuYUbDifI8I)

happens only with 'Debug' build type: works with 'Release' instead, so this can be closed
