### ISSUE TITLE
Some OGG can't be played

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#522]
It seems some OGG files can't be played in BZR2.

It can be played in BZR1.

BZR2's version: 2.0.71

example:
[rob.zip](https://github.com/aargirakis/BZRPlayer/files/15490775/rob.zip)

**Comment by aargirakis** [comment]
This is a 2.0.71 regression, worked in 2.0.70. I'll take a look.

**Comment by aargirakis** [comment]
Fixed for next version (2.0.72)
