### ISSUE TITLE
flac tracks broken playback (2.0.71 regression)

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#525]
[flac.zip](https://github.com/user-attachments/files/15532935/flac.zip)
seems caused by #517 fix

**Comment by aargirakis** [comment]
Some flac files can be identified by furnace as a .fur file. I will add a check in the Furnace plugin.

**Comment by ciros88** [comment]
uo

**Comment by aargirakis** [comment]
What?

**Comment by ciros88** [comment]
sorry was "up" lol
