### ISSUE TITLE
unplayable xm

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#540]
due to its filename i suppose:
[XM.zip](https://github.com/user-attachments/files/16163397/XM.zip)
@aargirakis  what do you think about?

**Comment by aargirakis** [comment]
Works fine here...

**Comment by ciros88** [comment]
yah because of zip compression... try this: https://amp.dascene.net/downmod.php?index=24965&application=AMP

**Comment by aargirakis** [comment]
Well, I guess that's because of a limitation of the filesystem in Windows. If I unpack the file I can play it. When is it unpayable for you?

**Comment by ciros88** [comment]
ok the thing it is the following:
the filename have trailing white spaces after the extension, but when unpacking it on windows they are automatically removed (since they are not allowed on ntfs i suppose): so a windows user will never have the unpacked file with original filename.
