### ISSUE TITLE
support for random also when cliking on previous song button

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#56]
now, pressing "previous track" button when random is active simply go to previous track in playlist

random on previous track action is supported generally in two manners:

A) the action of playing a previous track will select a random track (the most obvious to think i suppose)
B) the action of playing a previous track will play the last played track (simply reverse playing history order, likes vlc)

some considerations about:

I think nobody is really interested for having random while pressing on previous subsong (A): why would anyone do this?
But somebody can be interested to find and re-play a song in a playlist where the random is active (B): I myselft, very ofte,n want to find a song to hear it again or just read its title in a random played playlist, so i simply press on "previous" button.

**Comment by aargirakis** [comment]
Yes, B is the most normal way to go.
