### ISSUE TITLE
[FLOD *.dw] GUI freeze when trying to play *.dw files

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#66]

**Comment by aargirakis** [comment]
Bug in DW Player in FLOD

**Comment by ciros88** [comment]
you could try to update flod version. then, also try this:
catch any exception when loading the dw file with flod, if there is one then try with loading it with uade

**Comment by ciros88** [comment]
2.0.19Alpha:
- xenon ii and golden axe still crashes
- menace now playing, but with missing channels

[dw.zip](https://github.com/aargirakis/BZRPlayer/files/9623972/dw.zip)
