### ISSUE TITLE
unable to go on previous playlist track when playing One Must Fall! 3.psm

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#67]
this happens only if it is the middle of a playlist, not when it is the last track
[One Must Fall! 3.zip](https://github.com/aargirakis/BZRPlayer/files/8934065/One.Must.Fall.3.zip)

**Comment by aargirakis** [comment]
Can't reproduce, are you sure it's not the track before that have issues?

**Comment by ciros88** [comment]
yeah, im sorry. the tracks before was the problem, because they are not supported.
i will open an issue for adding that support, here i would discuss to which strategy use when trying to go on a previous tracks that doesnt load. 

for being able to understand that a track is unsupported it could be displayed as ~~Strikethrough~~

Then, a good strategy to handle with this issue situation is to display unsupported tracks with red color (means that become the currently selected one) when selected (ie by next/previous action) also if they are not really playing, so the user can proceed to go on on the previous, and then the previous of the previous and so on.

**Comment by ciros88** [comment]
you can now reproduce the exact situation using issue #70 tracks
