### ISSUE TITLE
unsupported *.psm tracks (Extreme Pinball)

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#70]
[unsupported psm tracks.zip](https://github.com/aargirakis/BZRPlayer/files/8937739/unsupported.psm.tracks.zip)

**Comment by aargirakis** [comment]
They work fine in libopenmpt, so the question is, should we use libopenmtp primarly instead of libxmp? Is it it generally better? LibxmpI's development has stalled a bit the last couple of years. I'll have to rewrite the pattern views in that case.

**Comment by ciros88** [comment]
Libopenmtp is definitely better
