### ISSUE TITLE
unable to set play cursor to beginning or end of a seekable track

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#78]
it can be only set after beginning or before the end of a track

**Comment by ciros88** [comment]
> it can be only set after beginning or before the end of a track

this is not completely true: today i can set cursor to the end of the track without problem (but still impossible to set at the very  beginning)

**Comment by aargirakis** [comment]
Tried a few .xm songs and I could seek both to start and end.

**Comment by ciros88** [comment]
![bzr](https://user-images.githubusercontent.com/84340161/178192341-f87266a2-897f-4842-a448-f750ec23e0c9.gif)
