### ISSUE TITLE
sometimes crashes when a playlist is deleted (within app)

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#81]

**Comment by ciros88** [comment]
should be related to #254

**Comment by aargirakis** [comment]
Really vague bug description and since https://github.com/aargirakis/BZRPlayer/issues/254 is closed, we should probably close it?

**Comment by ciros88** [comment]
I was wandering today about it. Yeah, im going to close it

**Comment by ciros88** [comment]
2.0.44.Alpha: download it, open it, then delete a playlist: it will crash
