### ISSUE TITLE
Hollywood_Poker.spl continues to silently play after the end

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#85]
[Hollywood_Poker.zip](https://github.com/aargirakis/BZRPlayer/files/9083917/Hollywood_Poker.zip)

**Comment by ciros88** [comment]
dunno if it is a real bug or not. do you have another player for trying?
also i dont know if is played entirely or not
ps. length is unknown

**Comment by Fabrice-Praxinos** [comment]
At what point do you think the track stops? Do you have a precise timing ? I will compare with DeliPlayer.

There are quite a few modules that have this kind of behaviour: it plays for a while and then nothing for a few minutes, then only you go to the next module.

**Comment by ciros88** [comment]
deliplayer correctly recognizes two subsongs, while bzr2 only 1 (that continue to plays silently for minutes), i think this is the issue
![deliplayer](https://user-images.githubusercontent.com/84340161/188559047-0da8d774-e0df-4589-a16f-ce8dab174400.png)
![immagine](https://user-images.githubusercontent.com/84340161/188559125-76631b70-ad77-4da4-a5f6-3455c6d59cbe.png)

**Comment by ciros88** [comment]
since 2.0.18Alpha bzr2 recognizes 2 distinct subsongs like deliplayer. hovewer:

- subsong 1 still continues to play after the end
- subsong 2 is played as the default one

**Comment by ciros88** [comment]
since 2.0.30.Alpha subsong 1 & 2 still continue to silently play after the end
