### ISSUE TITLE
tracks not playing correctly

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#86]
[bs1-song23-m.zip](https://github.com/aargirakis/BZRPlayer/files/9091079/bs1-song23-m.zip)

**Comment by aargirakis** [comment]
Plays fine with libopenmpt, so when we switch to that this bug is a goner,

**Comment by ciros88** [comment]
at about 4:08 sounds stops for a seconds
[nudity4.zip](https://github.com/aargirakis/BZRPlayer/files/9158072/nudity4.zip)
