### ISSUE TITLE
independent windows height

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#94]
when a window is docked, it's height depends on other windows height.
A more convenient strategy is to make windows height independent from each other

**Comment by ciros88** [comment]
Initial scenario:
![immagine](https://user-images.githubusercontent.com/84340161/181301924-18994a69-fb88-45e9-a1f3-6abd7d368a33.png)

Resizing track viewport will resize or other docked nearby windows:
![immagine](https://user-images.githubusercontent.com/84340161/181301946-64c2631a-43d7-49e0-aa40-a8bcb2c1a209.png)

Desidered result:
![immagine](https://user-images.githubusercontent.com/84340161/181301967-6c879238-e23a-42b5-afda-0940ece7a233.png)

**Comment by rayman3003** [comment]
Yeap. It's better to have separate, closable, attachable windows, for each section.

And I think the main playback windows, must be on top left of all windows. (& it must be the only non-closable windows)

**Comment by ciros88** [comment]
> Yeap. It's better to have separate, closable, attachable windows, for each section.
> 
> And I think the main playback windows, must be on top left of all windows. (& it must be the only non-closable windows)

maybe player controls window centered position makes bzr2 layout more..modern? dunno
but yeah, it could be non-closeable

**Comment by aargirakis** [comment]
This should be closed now, right?
